packageExtensions:
  "@actions/github@*":
    dependencies:
      undici: '*'

  "@mui/material-nextjs@*":
    peerDependencies:
      "@emotion/styled": "^11.11.0"

  "@sentry/nextjs@*":
    dependencies:
      "@opentelemetry/core": "^1.25.1"
      "@opentelemetry/instrumentation": "^0.53.0"
      "@opentelemetry/sdk-trace-base": "^1.26.0"

  "@sentry/utils@*":
    dependencies:
      "@sentry/webpack-plugin": "*"

yarnPath: .yarn/releases/yarn-4.5.2.cjs
