nodeLinker: node-modules

packageExtensions:
  "@mui/material-nextjs@*":
    peerDependencies:
      "@emotion/styled": "^11.11.0"

  "@sentry/nextjs@*":
    dependencies:
      "@opentelemetry/core": "^2.0.0"
      "@opentelemetry/sdk-trace-base": "^2.0.0"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
