packageExtensions:
  "@actions/github@*":
    dependencies:
      undici: '*'

  "@mui/material-nextjs@*":
    peerDependencies:
      "@emotion/styled": "^11.11.0"

yarnPath: .yarn/releases/yarn-4.5.1.cjs
